---
title: 'Homework 2: Categorical Data'
author: "Nicholas G Reich, for Biostats 743 at UMass-Amherst"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, eval=FALSE)
```

Your assignment should be submitted in two separate files by 8am on Wednesday October 4th. The first, should be an RMarkdown (.Rmd) or another format that dynamically compiles your write up and runs the code inside it. The second should be the PDF file that was reproducibly compiled using the first file. All figures should be generated by the code, none should be loaded directly. The homework files should be submitted using your shared Google Drive folder with the instructor. 


# Inference for tables with small counts

One limitation of chi-squared tests that arises frequently in practice is that their inference is based on assumptions that may only be valid with large-sample sizes. A classical alternative to a chi-squared test in situations where there is a small cell count (i.e. less than 5) is to use Fisher's exact test. Another alternative would be to use Bayesian inference, which does not rely on large-sample approximations.

## Question 1
Based on Table 1 from Denes et al (_American Journal of Epidemiology_, 1977, 105: 2), the authors were attempting to ascertain whether food-service workers were more likely to be sick when they had worked on a particular night where there had been a known outbreak of foodborne illness. [Acknowledgments to Brian Caffo for parts of this question.]

The data was

  &nbsp;    | Sick    | Not sick 
------------ | ------- | ------------
Worked       | 10      | 12
Did not work | 2       | 26

(a) Obtain a copy of the original paper and read it. (Note: this is a test of your library science skills. Do not obtain a copy of this paper from a classmate. Locate this paper online either via typical search engine or using the UMass Libraries.)
(b) Re-run the chi-squared test that the authors ran in the paper to test the null hypothesis that employees who worked that night were as likely as those who did not to get sick.
(c) Run Fisher's exact test on this data to test the same hypothesis.
(d) Use a Bayesian analysis to test the same hypothesis.
(e) Write a paragraph comparing the assumptions and results of the three methods.

## Question 2
Generalize the above setting to one where you have observations on $n=50$ individuals and the contingency table has multinomial structure as follows:

   &nbsp;          | Sick    | Not sick 
------------ | -------- | ------------
$X = 1$      | $\pi_{11}$| $\pi_{12}$
$X = 2$      | $\pi_{21}$| $\pi_{22}$

with $(\pi_{11}, \pi_{12}, \pi_{21}, \pi_{22}) = (0.3, 0.3, 0.05, 0.35)$. 

Conduct a simulation study comparing the performance of (1) a chi-squared test of independence testing whether the rows follow the same distribution, (2) Fisher's exact test, and the Bayesian method described in class using (3) uniform priors and (4) Jeffrey's priors for $\pi_{sick|x=2}$ and $\pi_{sick|x=2}$. Assuming a Type I error rate of 0.05, compare the statistical power of these four methods (i.e. how often does each method correctly reject the null hypothesis that $\pi_{sick|x=1}=\pi_{sick|x=1}$) using a simulation study. Assess the coverage rates for 80% and 95% posterior credible intervals from the Bayesian methods for the estimands (1) the relative risk of being sick comparing $X=1$ to $X=2$ and (2) the difference in conditional probabilities of being sick $\pi_{sick|x=2}-\pi_{sick|x=1}$. Summarize your findings in 1-2 paragraphs and 1-2 figures. 

# Contingency Table questions

## Question 3

Test your computer's random normal generator. Simulate 10,000 random normal deviates and test whether or not they appear to be normal with a chi-squared test. Explain your steps and interpret your results. [Acknowledgments to Brian Caffo for this question.]

## Question 4

The Chinese Mini-Mental Status Test (CMMS) is a test consisting of 114 items intended to identify people with Alzheimers disease (AD) and dementia among people in China. An extensive clinical evaluation was performed of this instrument, whereby participants were interviewed by psychiatrists and nurses and a definitive (clinical) diagnosis of AD was made. The table below shows the counts obtained on the sub-group of people with at least some formal education. Suppose a cutoff value of $\leq 20$ on the test is used to identify people with AD. [Acknowledgments to Brian Caffo for this question.]

 CMMS Score  | No AD   | AD 
------------ | ------- | ------------
0-5          | 0       | 2
6-10         | 0       | 1
11-15        | 3       | 4
16-20        | 9       | 5
21-25        | 16       | 3
26-30        | 18       | 1

(a) What is the sensitivity and specificity of the CMMS test using the 20 cutoff?
(b) Graph the positive predictive value as a function of the prevalence of AD. Do the same for the negative predictive value.
(c) What would be the sensitivity and specificity if a cutoff of 15 had been used?



# GLMs

## Question 5

Write your own R code for obtaining the MLEs and SEs for a Poisson GLM using two covariates. Conduct a small simulation study designed to stress-test your code and show that it can work in a variety of situations. Compare the results to the `glm()` function in R. Summarize the results and your experience in 1-2 paragraphs. [Acknowledgments to Ciprian Crainiceanu for this question.]


## Question 6

_CDA_ exercise 4.11

Table 4 is based on a study with Brithish doctors.
(a) For each age, find the sample coronary death rates per 1000 person-years for
nonsmokers and smokers. To compare them, take their ratio and describe its
dependence on age.

(b) Fit a main-effects model for the log rates using age and smoking as factors. In discussing
lack of fit, show that this model assumes a constant ratio of nonsmokers'
to smokers' coronary death rates over age.

(c) From part (a), explain why it is sensible to add a quantitative interaction of age
and smoking. For this model, show that the log ratio of coronary death rates
changes linearly with age. Assign scores to age, fit the model, and interpret.


\begin{table}[]
\centering
\caption{ 4.9 Data for Question 6 on Coronary Death Rates}
\begin{tabular}{ccccc}
\hline
      & \multicolumn{2}{c}{Person-years} & \multicolumn{2}{c}{Coronary Deaths} \\ \hline
Age   & Nonsmokers       & Smokers       & Nonsmokers         & Smokers        \\ \hline
35-44 & 18,793           & 52,407        & 2                  & 32             \\ \hline
45-54 & 10,673           & 43,248        & 12                 & 104            \\ \hline
55-64 & 5710             & 28,612        & 28                 & 206            \\ \hline
65-74 & 2585             & 12,663        & 28                 & 186            \\ \hline
75-84 & 1462             & 5317          & 31                 & 102            \\ \hline
\end{tabular}
\end{table}



## Question 7

_CDA_ exercise 4.12

Table 4.10 describes survival for 539 males diagnosed with lung cancer. The prognostic
factors are histology $(H)$ and state $(S)$ of disease. The assumption of a constant
rate over time is often not sensible, and this study divided the time scale $(T)$ into
two-month intervals and let the rate vary by the time interval. Let $\mu_{ijk}$ denote the
expected number of deaths and $t_{ijk}$ the total time at risk for histology $i$ and state
of disease $j$, in follow-up time interval $k$. Analyses suggested a lack of interaction
between $T$ and either prognostic factor (i.e., such proportional hazards models have
the same effects of $H$ and $S$ for each time interval).

(a) The main effects model

$$log(\mu_{ijk}/t_{ijk})=\alpha+\beta_{i}^H+\beta_{j}^S+\beta_k^T$$
has deviance 43.9. Explain why $df=52$. Does the model seems to fit adequately?

(b) For this model, interpret the estimated effects of $S$, 
 $$\hat{\beta_2^S}-\hat{\beta_1^S}=0.470(SE=0.174)$$
 $$\hat{\beta_3^S}-\hat{\beta_1^S}=1.324(SE=0.152)$$
(C) The model that adds an $S \times H$ interaction term has deviance 41.5 with $df = 48$.
Test whether a significantly improved fit results by allowing this interaction.


\begin{table}[]
\caption{Q7}
\label{my-label}
\begin{tabular}{ccccccccccc}
\hline
 &  & \multicolumn{9}{c}{Histology} \\ \hline
 & \begin{tabular}[c]{@{}c@{}}Disease\\ Stage\end{tabular} & \multicolumn{3}{c}{I} & \multicolumn{3}{c}{II} & \multicolumn{3}{c}{III} \\ \hline
Follow-upTimeInterval(months) &  & 1 & 2 & 3 & 1 & 2 & 3 & 1 & 2 & 3 \\ \hline
0-2 &  & 9 & 12 & 42 & 5 & 4 & 28 & 1 & 1 & 19 \\ \hline
 &  & (157 & 134 & 212 & 77 & 71 & 130 & 21 & 22 & 101) \\ \hline
2-4 &  & 2 & 7 & 26 & 2 & 3 & 19 & 1 & 1 & 11 \\ \hline
 &  & (139 & 110 & 136 & 68 & 63 & 72 & 17 & 18 & 63) \\ \hline
4-6 &  & 9 & 5 & 12 & 3 & 5 & 10 & 1 & 3 & 7 \\ \hline
 &  & (126 & 96 & 90 & 63 & 58 & 42 & 14 & 14 & 43) \\ \hline
6-8 &  & 10 & 10 & 10 & 2 & 4 & 5 & 1 & 1 & 6 \\ \hline
 &  & (102 & 86 & 64 & 55 & 42 & 21 & 12 & 10 & 32) \\ \hline
8-10 &  & 1 & 4 & 5 & 2 & 2 & 0 & 0 & 0 & 3 \\ \hline
 &  & (88 & 66 & 47 & 50 & 35 & 14 & 10 & 8 & 21) \\ \hline
10-12 &  & 3 & 3 & 4 & 2 & 1 & 3 & 1 & 0 & 3 \\ \hline
 &  & (82 & 59 & 39 & 45 & 32 & 13 & 8 & 8 & 14) \\ \hline
12+ &  & 1 & 4 & 1 & 2 & 4 & 2 & 0 & 2 & 3 \\ \hline
 &  & (76 & 51 & 29 & 42 & 28 & 7 & 6 & 6 & 10) \\ \hline
\end{tabular}
\end{table}

## Question 8

_CDA_ exercise 4.16

For binary data, define a GLM using the log link. Show that effects refer to the
relative risk. Why do you think this link is not often used? Hint: What happens if
the linear predictor takes a positive value?

## Question 9

_CDA_ exercise 4.21

A binomial GLM $\pi_i = \phi(\sum_j \beta_jx_{ij})$ with arbitrary inverse link function $\phi$ assumes
that $n_iY_i$ has a $bin(n_i,\pi_i)$ distribution. Find $w_i$, in (4.29) and hence $cov(\hat\beta)$. For
logistic regression, show that $w_i=n_i\pi_i(1-\pi_i)$.

## Question 10

_CDA_ exercise 4.27

For known $k$, show that the negative binomial distribution (4.13) has exponential
family form (4.1) with natural parameter $log[\mu/(\mu + k)]$.

<!--    - Bayesian example, BDA3 p 37
    - chisq GOF test on draws from some distribution
    - derivation of chi-sq being equivalent to square of test of proportions test stat
    - 652 HW3, problem 6: likelihood interval comparison to 
    - Poisson GOF test
    - Bayesian multinomial example
    -->
